CREATE TABLE h_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100),
    order_date DATE DEFAULT SYSDATE
);

INSERT INTO h_orders (customer_name)
VALUES ('John Doe');

select * from h_orders;

CREATE OR REPLACE PROCEDURE add_h_order (
    p_customer_name VARCHAR2
) AS
BEGIN
    INSERT INTO h_orders (customer_name, order_date)
    VALUES (p_customer_name, SYSDATE); -- auto‑insert current date
    
    COMMIT;
END;


BEGIN
    add_h_order('Alice Johnson');
END;

BEGIN
    add_h_order('Ram Raj');
END;


BEGIN
    add_h_order('John Max');
END;

BEGIN
    add_h_order('Mind Max');
END;

SELECT * FROM h_orders;

ROLLBACK;
